### ISSUE TITLE
How to build angularAMD using grunt uglify and concat?

### ISSUE THREAD

**Issue by chamviptela** [marcoslin/angularAMD#131]
"grunt-contrib-concat": "^0.4.0",
 "grunt-contrib-requirejs": "^0.4.4", (also used "grunt-contrib-uglify": "^0.4.0")
 "angularAMD": "~0.2.1",

I'm able to concat and minify my application js using the above libs (using requirejs to 'uglify' the code). When deploying on to dev server and entering the main.js entry point in index.html, I incur this error: Uncaught Error: Mismatched anonymous define() module: function (app) { app.controller("AdminController", [ "$scope", function($scope) {  ...  } ]);
}

I saw in your example code, you minified the code but didn't concat to one file. Any clue to what maybe causing this error I'm seeing above?

**Comment by blackanthrax** [comment]
Why would you concat your js files? RequireJS is dependency management and it's purpose is to load only code that is needed at a certain point. By concatenating you would simply make RequireJS obsolete.
