### ISSUE TITLE
angularAMD still alive?

### ISSUE THREAD

**Issue by RobertjanTuit** [marcoslin/angularAMD#134]
This looks like an awesome library, and would save us from having to do a lot of this ourselves.

But looking at the open issues, and commit history, is it right to assume this is no longer being worked on, should we be looking at something else, will this be supported forward, or does it just need more contributors?

Thanks in advance,
_Rj

**Comment by marcoslin** [comment]
I use it....

The only problem is that my day job has been taking up all my times lately so no time left dedicate to angularAMD.  I truly feel bad.

More contributor will definitely help. Those interested, please do let me know.

Our project (day job) is going live next week.  So hopefully I will have more time then.

**Comment by RobertjanTuit** [comment]
Thanks Marcos! Good to know it is still alive, would be a huge waste otherwise :) 
We'll consider contributing once we start using it in our current project.

**Comment by mpiasta-ca** [comment]
I'm using AngularAMD in our project. Everything is working great, but [I could use some angularAMD.config(...) support](https://github.com/marcoslin/angularAMD/issues/123) so I can split my `app.js` file into smaller chunks of code.
