### ISSUE TITLE
cdn - 3rd party libs

### ISSUE THREAD

**Issue by msimonc** [marcoslin/angularAMD#139]
The Readme for this project show an example main.js with a cdn url for angular
but the main.js in the sample project (and this one) points to the local build bower angular instead.

When I change it I get:  
`Error: ENOENT, no such file or directory '//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.min.js'`
on grunt build with or without the https

**Comment by marcoslin** [comment]
You can find the correct AngularJS CDN in their [home page](https://angularjs.org/).
