### ISSUE TITLE
versioning of views?

### ISSUE THREAD

**Issue by jasoncavaliere** [marcoslin/angularAMD#140]
I'm looking for a way to allow caching of an HTML view but force an update on refresh.  I tried adding a query string parameter to my view names, but the  angularAMD.route() method seems to ignore it.

I have a route table in a requireJS module that looks like this: 

define(['angularAMD'], function (angularAMD) {
    'use strict';
    var viewVersion = '?v=1.4';
    var routes = {}
    routes.authenticated ={};
    routes.unauthenticated={};
    routes.unauthenticated.home= angularAMD.route({
        url: '/home',
        templateUrl: 'views/home.html' + viewVersion,
        controller: 'homeController',
        controllerUrl: 'controllers/home'
    });
/// Other routes here....
return routes;
});

Is there a way to accomplish what I'm trying to do here?

**Comment by marcoslin** [comment]
angularAMD.route was designed to be used by [ngRoute](https://docs.angularjs.org/api/ngRoute) or [ui-router](https://github.com/angular-ui/ui-router).  It is not clear which router you are using here.

**Comment by jasoncavaliere** [comment]
I'm using ui-router.  

Date: Mon, 25 May 2015 13:27:32 -0700

**Comment by marcoslin** [comment]
That should work then.  Have you checked your developer console and confirmed that the url is indeed not being passed?  Does the same code works without angularAMD.route?

**Comment by marcoslin** [comment]
Closed without further comment from user.
