### ISSUE TITLE
Modulaize your app

### ISSUE THREAD

**Issue by stevezau** [marcoslin/angularAMD#144]
Hi,

I've been reading issue https://github.com/marcoslin/angularAMD/issues/45 and i want to clarify.

When using angularAMD you are expected to register controllers etc via the app.register function. You cannot register new modules? So, using angularAMD i cannot split my application into several modules?

Is that a correct statement?

**Comment by marcoslin** [comment]
#45 is a bit old so please follow the updated syntax per:

https://github.com/marcoslin/angularAMD#creating-a-module

If you split your app into modules, you can use [ngload](https://github.com/marcoslin/angularAMD#3rd-party-angularjs-modules) to load the angular module you created.

Personally, I no longer create modules as all my reusable code are in form of `.factory` or `.service` and I would just load them as needed.
