### ISSUE TITLE
Cannot bower install with angular 1.4.2

### ISSUE THREAD

**Issue by tomin** [marcoslin/angularAMD#146]
We're using angular 1.4.2 and bower.
Can you test angularAMD on angular 1.4.2?
If it works, please free the dependency constraint.
Thanks 

```
bower install https://github.com/marcoslin/angularAMD.git                                       /cygdrive/t/builds/tps_32_6_10/target/sources/sto/apps/web/a10gui/frontend
bower angularAMD#*          not-cached https://github.com/marcoslin/angularAMD.git#*
bower angularAMD#*             resolve https://github.com/marcoslin/angularAMD.git#*
bower angularAMD#*            checkout v0.2.1
bower angularAMD#*        invalid-meta angularAMD is missing "main" entry in bower.json
bower angularAMD#*        invalid-meta angularAMD is missing "ignore" entry in bower.json
bower angularAMD#*            resolved https://github.com/marcoslin/angularAMD.git#0.2.1
bower angular#1.2.21        not-cached git://github.com/angular/bower-angular.git#1.2.21
bower angular#1.2.21           resolve git://github.com/angular/bower-angular.git#1.2.21
bower requirejs#~2.1.9          cached git://github.com/jrburke/requirejs-bower.git#2.1.18
bower requirejs#~2.1.9        validate 2.1.18 against git://github.com/jrburke/requirejs-bower.git#~2.1.9
bower angular#1.2.21          download https://github.com/angular/bower-angular/archive/v1.2.21.tar.gz
bower angular#1.2.21           extract archive.tar.gz
bower angular#1.2.21      invalid-meta angular is missing "ignore" entry in bower.json
bower angular#1.2.21          resolved git://github.com/angular/bower-angular.git#1.2.21
bower angular#~1.4.2            cached git://github.com/angular/bower-angular.git#1.4.2
bower angular#~1.4.2          validate 1.4.2 against git://github.com/angular/bower-angular.git#~1.4.2
bower angular#1.4.2             cached git://github.com/angular/bower-angular.git#1.4.2
bower angular#1.4.2           validate 1.4.2 against git://github.com/angular/bower-angular.git#1.4.2
bower angular#~1.x              cached git://github.com/angular/bower-angular.git#1.4.2
bower angular#~1.x            validate 1.4.2 against git://github.com/angular/bower-angular.git#~1.x
bower angular#>=1.3.0           cached git://github.com/angular/bower-angular.git#1.4.2
bower angular#>=1.3.0         validate 1.4.2 against git://github.com/angular/bower-angular.git#>=1.3.0
bower angular#>=1.2.0           cached git://github.com/angular/bower-angular.git#1.4.2
bower angular#>=1.2.0         validate 1.4.2 against git://github.com/angular/bower-angular.git#>=1.2.0
bower                        ECONFLICT Unable to find suitable version for angular
```

**Comment by tomin** [comment]
I notice that the bower.json in this repo is correct.
"angular": "^1.3.0",

But online version uses another repo version.
https://github.com/marcoslin/bower-angularAMD/blob/master/bower.json
"angular": "~1.2.0",


bower info angularAMD                                                                           
bower angularAMD#*              cached git://github.com/marcoslin/bower-angularAMD.git#0.2.1
bower angularAMD#*            validate 0.2.1 against git://github.com/marcoslin/bower-angularAMD.git#*

{
  name: 'angularAMD',
  description: 'Facilitate use of RequireJS in AngularJS ',
  version: '0.2.1',
  main: 'angularAMD.js',
  license: 'MIT',
  keywords: [
    'angularjs',
    'requirejs'
  ],
  authors: [
    'Marcos Lin (https://github.com/marcoslin/)'
  ],
  repository: {
    type: 'git',
    url: 'git@github.com:marcoslin/angularAMD.git'
  },
  dependencies: {
    angular: '~1.2.0',
    requirejs: '~2.1.0'
  },
  homepage: 'https://github.com/marcoslin/bower-angularAMD'
}

Available versions:
  - 0.2.1
  - 0.2.0
  - 0.1.1
  - 0.1.0
  - 0.0.2
  - 0.0.1
You can request info for a specific version with 'bower info angularAMD#<version>'

**Comment by marcoslin** [comment]
There is a bug with 1.4.x as per #138 that I have not had a chance to fix yet.  If you do not lazy load animations, you should be able to fix it by adding the following to your `bower.json`:

```
{
  "dependencies": {
    ...
  },
  "resolutions": {
    "angular": "~1.4.2"
  }
}
```

I will free the dependency when (if) #138 is fixed.

**Comment by tylercollier** [comment]
+1

I look forward to using AngularAMD with Angular 1.4 (with no workarounds). Thanks!

**Comment by OronNadiv** [comment]
+1
