### ISSUE TITLE
angularAMD.route and require optimization, r.js

### ISSUE THREAD

**Issue by jacobnijgh** [marcoslin/angularAMD#151]
Hi there, i am using the angularAMD.route method which works fine in non compressed mode but after optimization it is searching for the file url(404) instead of looking in the optimized/compressed file. 

What is the correct way to use angularAMD and routes so that the Require optimization would still work.
Thanks in advance!

**Comment by marcoslin** [comment]
Please take a look at a sample project I created:

https://github.com/marcoslin/angularAMD-sample

Do reopen this issue if there are further questions.
