### ISSUE TITLE
angularAMD + UI Router + Multiple named views

### ISSUE THREAD

**Issue by hassancode** [marcoslin/angularAMD#156]
Hi, 
I am just exploring angularAMD to use in my project, its been working great, but just not sure how should i configure for multiple named views, 

<h4>about.html:</h4>
<div>
    <h1>The About Page</h1>
    <p>This page demonstrates <span class="text-danger">multiple</span> and <span class="text-danger">named</span> views.</p>
</div>
<div class="row">
    <div class="col-sm-6">
<h1>ColumnOne View</h1>
        <div ui-view="columnOne"></div>
    </div>
    <div class="col-sm-6">
<h1>ColumnTwo View</h1>
        <div ui-view="columnTwo"></div>
    </div>
</div>

<h4>app.config.js:</h4>
 .state('about', angularAMD.route({
                    url: '/about',
                    templateUrl: 'app/partials/about.html',
                    'columnOne@about': { template: 'Look I am a column!' },
                    'columnTwo@about': {
                        templateUrl: 'app/partials/table-data.html',
                        controller: 'scotchController'
                    }
                }));

I cannot show the columnone and columntwo besides about html.

**Comment by mrmofo** [comment]
If I had to guess without looking at all the code I would recommend trying this:

```javascript
angular.state('about', {
    url: '/about',
    templateUrl: 'app/partials/about.html',
    'columnOne@about': { template: 'Look I am a column!' },
    'columnTwo@about': angularAMD.route({
        templateUrl: 'app/partials/table-data.html',
        controller: 'scotchController'
    })
});
```

If you don't have a controller for the other two views you don't need to use angularAMD.route() with them. 

If this doesn't work - set up a plunker with your problem and link it.

Best,
Mike

**Comment by hassancode** [comment]
I am sorry Mike, the code I posted above was missing views {}, and I also applied angularAMD.route only where needed as you said, we don't need if we don't controller to the view as below:

.state('about', {
                        url: '/about',
                        views: {
                            // the main template will be placed here (relatively named)
                            '': { templateUrl: 'app/partials/about.html' },

                            // the child views will be defined here (absolutely named)
                            'columnOne@about': { template: 'Look I am a column!' },

                            // for column two, we'll define a separate controller 
                            'columnTwo@about': angularAMD.route({
                                templateUrl: 'app/partials/table-data.html',
                                controller: 'scotchController',
                                controllerAs: 'table',
                                controllerUrl: 'app/partials/scotch.controller'
                            })
                        }

                    });

Thanks alot Mike, closing the issue now.
