### ISSUE TITLE
ng-Controllers on index.html site

### ISSUE THREAD

**Issue by dmoshfegh** [marcoslin/angularAMD#16]
Is there a way to use ng-controllers on the main site outside of the ng-view? 
Why: We want to display a dynamic navigation. Therefore we need a ng-controller on our index.html
Atm. we resolved this issue with ng-include on the subsites and put the ng-view on the body...

**Comment by priyank2005** [comment]
How to load service using ngload in this?

**Comment by kudeshiyah** [comment]
hello there, link you provided (http://plnkr.co/edit/azsKJnFJ0pYwBW0dGMFH?p=preview) is not working.
plz check
