### ISSUE TITLE
$httpBackend 'No pending request to flush' when angularAMD.inject([ResourceService])

### ISSUE THREAD

**Issue by sandust** [marcoslin/angularAMD#87]
It seems that $httpBackend doesn't hook up correctly with $resource services loaded through ngload/angularAMD.inject.

I'm not sure if there is supposed to be a better way to do this, but I can't test any $resource using $httpBackend due to this error.

Here's a plunker example: http://plnkr.co/edit/xYYFWoJhWQ637QFL0jpF?p=preview

The plunker fails intermittently (I'm probably messing up the order) so you have to click the refresh or edit something to until it "works". Uncommenting the last 2 lines in the resourceSpec.js to try it directly works, showing that the problem might be by loading the service through angularAMD.

Am I doing something wrong here? or is this a bug?

**Comment by pedrotcaraujo** [comment]
Hi marcoslin, I'm trying to do the same thing, and your sample code is working perfect, but I think that code a little bit stranger, does not it?

I mean,  to inject ngMock in my app.js file. I just wanna inject ngMock when I'm running tests.

What you think about it?

**Comment by marcoslin** [comment]
I am pretty sure that's how ngMock works:
https://docs.angularjs.org/api/ngMock

It unfortunately cannot be lazy loaded, or at least I did not manage to lazy load ngMock.  As result, I normally have a different app.js created just to run my tests.
