### ISSUE TITLE
AngularUI Router

### ISSUE THREAD

**Issue by freeman42x** [marcoslin/angularAMD#9]
Is it possible to use angularAMD with [AngularUI Router](https://github.com/angular-ui/ui-router)? The routing in ui-router being done with `$stateProvider` and `$urlRouterProvider` (for default route).

**Comment by riccardoroasio** [comment]
Hi,

i'm trying to use ui-router multiple views in this way:

` .state('main', {
            url:'/app',
        //    abstract: true,
            data: {requireLogin:true },
            views:{
             '':
               angularAMD.route({
                templateUrl:function (){ var token=$cookies.get('token'); return '/getTemplate/'+token+'/main'; },
                controller:''
               }),
             'main.content@main':
               angularAMD.route({
                templateUrl:function (){ console.log("main.content template"); var token=$cookies.get('token'); return '/getTemplate/'+token+'/main.content'; },
                controller:'main.content',
                controllerUrl:function (){ console.log("main.content controller");var token=$cookies.get('token'); return '/getController/'+token+'/main.content.js'; }//'main.content'
               }),`

but it seems not to work... what i'm doing wrong?

Thanks,
Riccardo
