### ISSUE TITLE
$httpProvider.interceptors

### ISSUE THREAD

**Issue by hawkwind2** [marcoslin/angularAMD#96]
Another one please, how do I use that code in AMD?
When we have $routeProvider...

app.config(function ($httpProvider) {
    $httpProvider.interceptors.push('authInterceptorService');
});

**Comment by angular-moon** [comment]
动态加载的模块里的 app.config(function ($httpProvider) {
$httpProvider.interceptors.push('authInterceptorService');
});
拦截器没有执行

**Comment by marcoslin** [comment]
@angular-moon `app.config` must be ran before calling `angularAMD.bootstrap` for it to work.
